### PR TITLE
Fixed issue #7 where the clipboard didnt save to a bin file

### PR DESCRIPTION
**Pull request by kokkie20**
Fixed issue #7 
Now it does save to a bin file in the chosen directory

### CODE REVIEW

**Comment by kokkie20** [comment]
Use only:
Helper_Class.cs
Main_Form.cs

*Ignore the rest, sorry kinda new to github stuff.....

**Comment by AcK77** [comment]
Hi, glad to see one dev want to fix present bug in AmiiBomb :)!
Just a little request, can you do another Pull Request with just the two above file in it?
Because right now you add the *.csproj and .gitignore files. Thanks ^^!

**Comment by kokkie20** [comment]
I will try to set a new one up :D 
Kinda new to the github part so need to test a lot of stuff to get it good working :P

**Comment by AcK77** [comment]
No problem about this mistake ^^! I'm new to github too :P and one thing I know it's when a thing is applied it's really hard to partially get it back lol! I close this Pull Request and waiting the new one with the two needed files :)!

**Pull request closed without merging**
